os:
  - linux

language: cpp
dist: xenial

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -q

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - catch
      - cmake
      - doxygen
      - cppcheck

branches:
  only:
    - master
    - devel

script:

  - export CC=gcc-9;
  - export CXX=g++-9;
  - mkdir -p build && cd build
  - cmake -DLIBRA_TESTS=yes ..
  - make unit-tests -j 4
  - make test
